logging:
  level:
    root: off

spring:
  main:
    banner-mode: off

# 기상청 단기예보 조회서비스 API 설정
# API 키 발급: https://www.data.go.kr/data/15084084/openapi.do
weather:
  api:
    service-key:
    url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
